name: org-ci-blueprint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Markdown lint (mdl via docker)
        run: docker run --rm -v $PWD:/work tmknom/mdl:latest mdl -r ~MD013 ~MD033 /work

  meta-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Ensure key files exist
        run: |
          test -f README.md
          test -f LICENSE
          test -f SECURITY.md
          test -f CODE_OF_CONDUCT.md
          test -f docs/ROADMAP.md
