name: ossf-scorecard
on:
  schedule:
    - cron: '43 4 * * 4'
  push:
    branches: [ main ]
permissions: read-all
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
